[package]
name = "rust-interpretor"
version = "0.1.0"
authors = ["jtavera235 <jtavera235@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
